baseURL = 'https://oreilly-japan.github.io/OpenEndedCodebook/'
languageCode = 'ja'
title = 'Pythonではじめるオープンエンドな進化的アルゴリズム - 発散型の機械学習による多様な解の探索'
publishDir = '../../public'
contentDir = "../appendix/"

[markup]
  [markup.highlight]
    anchorLineNos = false
    codeFences = true
    guessSyntax = false
    hl_Lines = ''
    hl_inline = false
    lineAnchors = ''
    lineNoStart = 1
    lineNos = false
    lineNumbersInTable = true
    noClasses = true
    noHl = false
    style = 'monokai'
    tabWidth = 4
    
[markup.goldmark.renderer]
unsafe = true
