name: Deploy to AWS Lambda

on:
  push:
    branches:
      - work-branch-Okada  # デプロイしたいブランチ名を指定

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Node.js environment
      uses: actions/setup-node@v2
      with:
        node-version: '14'  # 使用するNode.jsのバージョンを指定

    - name: Install dependencies
      run: npm install

    - name: Zip the code
      run: zip -j function.zip src/prompt_base/lambda_functions.py

    - name: Assume IAM role
      id: assume-role
      uses: aws-actions/configure-aws-credentials@v2
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ secrets.AWS_REGION }}
        role-to-assume: arn:aws:iam::871813978388:role/lambda-deploy-role-AIGen
        role-duration-seconds: 3600

    - name: Deploy to AWS Lambda
      run: |
        aws lambda update-function-code \
          --function-name generative_girl_2 \
          --zip-file fileb://function.zip \
          --region ${{ secrets.AWS_REGION }}
